# Script simple para renombrar migraciones

# Migraciones con 1 dígito
Rename-Item "07_create_apartamentos.php" "007_create_apartamentos.php" -ErrorAction SilentlyContinue
Rename-Item "08_create_estado.php" "008_create_estado.php" -ErrorAction SilentlyContinue
Rename-Item "09_create_clientes.php" "009_create_clientes.php" -ErrorAction SilentlyContinue

# Migraciones con 2 dígitos
Rename-Item "10_create_reservas.php" "010_create_reservas.php" -ErrorAction SilentlyContinue
Rename-Item "11_create_estado_realizar_apartamento.php" "011_create_estado_realizar_apartamento.php" -ErrorAction SilentlyContinue
Rename-Item "12_create_realizar_apartamento.php" "012_create_realizar_apartamento.php" -ErrorAction SilentlyContinue
Rename-Item "13_create_photo_categoria.php" "013_create_photo_categoria.php" -ErrorAction SilentlyContinue
Rename-Item "14_create_photos.php" "014_create_photos.php" -ErrorAction SilentlyContinue
Rename-Item "15_create_clientes_update.php" "015_create_clientes_update.php" -ErrorAction SilentlyContinue
Rename-Item "16_update_reserva.php" "016_update_reserva.php" -ErrorAction SilentlyContinue
Rename-Item "17_update_reserva.php" "017_update_reserva.php" -ErrorAction SilentlyContinue
Rename-Item "18_update_reserva.php" "018_update_reserva.php" -ErrorAction SilentlyContinue
Rename-Item "19_update_photo.php" "019_update_photo.php" -ErrorAction SilentlyContinue
Rename-Item "20_update_realizar_table.php" "020_update_realizar_table.php" -ErrorAction SilentlyContinue
Rename-Item "21_update_user.php" "021_update_user.php" -ErrorAction SilentlyContinue
Rename-Item "22_update_ photos.php" "022_update_ photos.php" -ErrorAction SilentlyContinue
Rename-Item "23_update_photos.php" "023_update_photos.php" -ErrorAction SilentlyContinue
Rename-Item "24_create_whatsapp.php" "024_create_whatsapp.php" -ErrorAction SilentlyContinue
Rename-Item "25_create_chat_gpt.php" "025_create_chat_gpt.php" -ErrorAction SilentlyContinue
Rename-Item "26_create_mensaje.php" "026_create_mensaje.php" -ErrorAction SilentlyContinue
Rename-Item "27_create_mensaje_auto_categoria.php" "027_create_mensaje_auto_categoria.php" -ErrorAction SilentlyContinue
Rename-Item "28_create_mensaje_auto.php" "028_create_mensaje_auto.php" -ErrorAction SilentlyContinue
Rename-Item "29_create_huesped.php" "029_create_huesped.php" -ErrorAction SilentlyContinue
Rename-Item "30_update_photos.php" "030_update_photos.php" -ErrorAction SilentlyContinue
Rename-Item "31_update_clientes.php" "031_update_clientes.php" -ErrorAction SilentlyContinue
Rename-Item "32_update_apartamentos.php" "032_update_apartamentos.php" -ErrorAction SilentlyContinue
Rename-Item "33_update_clientes.php" "033_update_clientes.php" -ErrorAction SilentlyContinue
Rename-Item "34_update_clientes.php" "034_update_clientes.php" -ErrorAction SilentlyContinue
Rename-Item "35_update_cliente.php" "035_update_cliente.php" -ErrorAction SilentlyContinue
Rename-Item "36_update_clientes.php" "036_update_clientes.php" -ErrorAction SilentlyContinue
Rename-Item "37_update_huesped.php" "037_update_huesped.php" -ErrorAction SilentlyContinue
Rename-Item "38_update_huesped.php" "038_update_huesped.php" -ErrorAction SilentlyContinue
Rename-Item "39_create_comprobacion.php" "039_create_comprobacion.php" -ErrorAction SilentlyContinue
Rename-Item "40_create_estados_mensajes.php" "040_create_estados_mensajes.php" -ErrorAction SilentlyContinue
Rename-Item "41_update_apartamentos_edificio.php" "041_update_apartamentos_edificio.php" -ErrorAction SilentlyContinue
Rename-Item "42_update_apartamentos.php" "042_update_apartamentos.php" -ErrorAction SilentlyContinue
Rename-Item "43_update_chatgpt.php" "043_update_chatgpt.php" -ErrorAction SilentlyContinue
Rename-Item "44_create_configuracion.php" "044_create_configuracion.php" -ErrorAction SilentlyContinue
Rename-Item "45_update_configuracion.php" "045_update_configuracion.php" -ErrorAction SilentlyContinue
Rename-Item "46_create_reparaciones.php" "046_create_reparaciones.php" -ErrorAction SilentlyContinue
Rename-Item "47_create_fichajes.php" "047_create_fichajes.php" -ErrorAction SilentlyContinue
Rename-Item "48_create_pausas.php" "048_create_pausas.php" -ErrorAction SilentlyContinue
Rename-Item "49_create_bancos.php" "049_create_bancos.php" -ErrorAction SilentlyContinue
Rename-Item "50_create_categoria_gastos.php" "050_create_categoria_gastos.php" -ErrorAction SilentlyContinue
Rename-Item "51_create_gasto.php" "051_create_gasto.php" -ErrorAction SilentlyContinue
Rename-Item "52_update_gastos.php" "052_update_gastos.php" -ErrorAction SilentlyContinue
Rename-Item "53_create_estados_gastos.php" "053_create_estados_gastos.php" -ErrorAction SilentlyContinue
Rename-Item "54_create_estados_ingresos.php" "054_create_estados_ingresos.php" -ErrorAction SilentlyContinue
Rename-Item "55_create_categoria_ingresos.php" "055_create_categoria_ingresos.php" -ErrorAction SilentlyContinue
Rename-Item "56_create_ingresos.php" "056_create_ingresos.php" -ErrorAction SilentlyContinue
Rename-Item "57_update_reservas.php" "057_update_reservas.php" -ErrorAction SilentlyContinue
Rename-Item "58_create_cuentas_contable.php" "058_create_cuentas_contable.php" -ErrorAction SilentlyContinue
Rename-Item "59_create_grupo_contable.php" "059_create_grupo_contable.php" -ErrorAction SilentlyContinue
Rename-Item "60_create_sub_cuentas_contable.php" "060_create_sub_cuentas_contable.php" -ErrorAction SilentlyContinue
Rename-Item "61_create_sub_cuenta_hija.php" "061_create_sub_cuenta_hija.php" -ErrorAction SilentlyContinue
Rename-Item "62_create_sub_grupo_contable.php" "062_create_sub_grupo_contable.php" -ErrorAction SilentlyContinue
Rename-Item "63_create_formas_pago.php" "063_create_formas_pago.php" -ErrorAction SilentlyContinue
Rename-Item "64_create_diario_caja.php" "064_create_diario_caja.php" -ErrorAction SilentlyContinue
Rename-Item "65_update_limpieza.php" "065_update_limpieza.php" -ErrorAction SilentlyContinue
Rename-Item "66_update_user.php" "066_update_user.php" -ErrorAction SilentlyContinue
Rename-Item "67_create_anio.php" "067_create_anio.php" -ErrorAction SilentlyContinue
Rename-Item "68_update_anio.php" "068_update_anio.php" -ErrorAction SilentlyContinue
Rename-Item "69_update_anio.php" "069_update_anio.php" -ErrorAction SilentlyContinue
Rename-Item "70_create_estados_diario.php" "070_create_estados_diario.php" -ErrorAction SilentlyContinue
Rename-Item "71_update_diario_caja.php" "071_update_diario_caja.php" -ErrorAction SilentlyContinue
Rename-Item "72_create_prompt_asistente.php" "072_create_prompt_asistente.php" -ErrorAction SilentlyContinue
Rename-Item "73_create_email_notificaciones.php" "073_create_email_notificaciones.php" -ErrorAction SilentlyContinue
Rename-Item "74_update_tecnico.php" "074_update_tecnico.php" -ErrorAction SilentlyContinue
Rename-Item "75_update_tecnico.php" "075_update_tecnico.php" -ErrorAction SilentlyContinue
Rename-Item "76_create_limpiadora_guardia.php" "076_create_limpiadora_guardia.php" -ErrorAction SilentlyContinue
Rename-Item "77_create_edificio.php" "077_create_edificio.php" -ErrorAction SilentlyContinue
Rename-Item "78_update_apartamentos.php" "078_update_apartamentos.php" -ErrorAction SilentlyContinue
Rename-Item "79_limpieza_fondo.php" "079_limpieza_fondo.php" -ErrorAction SilentlyContinue
Rename-Item "80_create_checklists.php" "080_create_checklists.php" -ErrorAction SilentlyContinue
Rename-Item "81_create_items_checklists.php" "081_create_items_checklists.php" -ErrorAction SilentlyContinue
Rename-Item "82_create_controles_limpieza.php" "082_create_controles_limpieza.php" -ErrorAction SilentlyContinue
Rename-Item "83_update_limpieza.php" "083_update_limpieza.php" -ErrorAction SilentlyContinue
Rename-Item "84_create_proveedores.php" "084_create_proveedores.php" -ErrorAction SilentlyContinue
Rename-Item "85_create_apartamento_item_checklist.php" "085_create_apartamento_item_checklist.php" -ErrorAction SilentlyContinue
Rename-Item "86_create_invoices_status.php" "086_create_invoices_status.php" -ErrorAction SilentlyContinue
Rename-Item "87_create_invoices.php" "087_create_invoices.php" -ErrorAction SilentlyContinue
Rename-Item "88_create_invoice_reference_autoincrement.php" "088_create_invoice_reference_autoincrement.php" -ErrorAction SilentlyContinue
Rename-Item "89_update_invoices.php" "089_update_invoices.php" -ErrorAction SilentlyContinue
Rename-Item "90_create_temporadas.php" "090_create_temporadas.php" -ErrorAction SilentlyContinue
Rename-Item "91_create_tarifas.php" "091_create_tarifas.php" -ErrorAction SilentlyContinue
Rename-Item "92_create_invoice_concepts.php" "092_create_invoice_concepts.php" -ErrorAction SilentlyContinue
Rename-Item "93_create_emails.php" "093_create_emails.php" -ErrorAction SilentlyContinue
Rename-Item "94_create_status_email.php" "094_create_status_email.php" -ErrorAction SilentlyContinue
Rename-Item "95_create_category_email.php" "095_create_category_email.php" -ErrorAction SilentlyContinue
Rename-Item "96_update_email.php" "096_update_email.php" -ErrorAction SilentlyContinue
Rename-Item "97_create_checklist_photo_requirements.php" "097_create_checklist_photo_requirements.php" -ErrorAction SilentlyContinue
Rename-Item "98_update_photo.php" "098_update_photo.php" -ErrorAction SilentlyContinue
Rename-Item "99_create_photo_requirements.php" "099_create_photo_requirements.php" -ErrorAction SilentlyContinue

Write-Host "Renombrado completado!"
